name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest

  

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'node'
          cache: 'npm'  

      # Install dependencies and build Storybook
      - name: Install dependencies and build Storybook
        working-directory: ./client
        run: |
          npm install
      - name: Build Storybook
        working-directory: ./client
        run: |
          npm run build-storybook
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./client/docs

# Deploy the Storybook build to GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
